version: '3'
services:
  frontend:
    image: "nishantchouhan/currency-utilities-app:latest"
    ports:
      - "4000:80"
    environment:
      - PORT=80
  backend:
    image: "nishantchouhan/currency-utilities-server:latest"
    ports:
      - "5000:5000"  
    environment:
       - SERVER_PORT=5000