version: '3'
services:
  frontend:
    image: "nishantchouhan/currency-utilities-app"
    ports:
      - "4000:80"
  backend:
    image: "nishantchouhan/currency-utilities-server"
    ports:
      - "5000:5000"  
    